import type { MasterKampus, CalonSantri, PenempatanResult, Panitia } from './types';

export const mockKampus: MasterKampus[] = [
  {
    id_kampus: 1,
    nama_kampus: 'Gontor 1 Pusat',
    jenis_kelamin: 'Laki-laki',
    kapasitas_total: 1000,
    kuota_pelajar_baru: 200,
    kuota_terisi: 150,
    status_aktif: true,
    tanggal_dibuat: '2023-01-15',
    wakil_pengasuh: 'Ustadz Hasanuddin',
  },
  {
    id_kampus: 2,
    nama_kampus: 'Gontor 2',
    jenis_kelamin: 'Laki-laki',
    kapasitas_total: 800,
    kuota_pelajar_baru: 150,
    kuota_terisi: 150,
    status_aktif: true,
    tanggal_dibuat: '2023-01-15',
    wakil_pengasuh: 'Ustadz Ridwan Kamil',
  },
  {
    id_kampus: 3,
    nama_kampus: 'Gontor Putri 1',
    jenis_kelamin: 'Perempuan',
    kapasitas_total: 1200,
    kuota_pelajar_baru: 250,
    kuota_terisi: 220,
    status_aktif: true,
    tanggal_dibuat: '2023-01-16',
    wakil_pengasuh: 'Ustadzah Aisyah Humaira',
  },
  {
    id_kampus: 4,
    nama_kampus: 'Gontor Putri 2',
    jenis_kelamin: 'Perempuan',
    kapasitas_total: 900,
    kuota_pelajar_baru: 180,
    kuota_terisi: 180,
    status_aktif: true,
    tanggal_dibuat: '2023-01-16',
    wakil_pengasuh: 'Ustadzah Fatimah Azzahra',
  },
  {
    id_kampus: 5,
    nama_kampus: 'Gontor 3',
    jenis_kelamin: 'Laki-laki',
    kapasitas_total: 500,
    kuota_pelajar_baru: 100,
    kuota_terisi: 80,
    status_aktif: false,
    tanggal_dibuat: '2023-01-17',
    wakil_pengasuh: 'Ustadz Abdul Somad',
  },
];

export const mockSantri: CalonSantri[] = [
  {
    id_santri: 101,
    no_pendaftaran: '202401001',
    nama_lengkap: 'Ahmad Fathan',
    jenis_kelamin: 'Laki-laki',
    nilai_bindonesia: 85.5,
    nilai_imla: 90.0,
    nilai_alquran: 92.5,
    nilai_berhitung: 88.0,
    rata_rata_ujian: 89.0,
    status_penempatan: 'Ditempatkan',
  },
  {
    id_santri: 102,
    no_pendaftaran: '202402002',
    nama_lengkap: 'Zainab Aliyah',
    jenis_kelamin: 'Perempuan',
    nilai_bindonesia: 91.0,
    nilai_imla: 88.5,
    nilai_alquran: 94.0,
    nilai_berhitung: 87.0,
    rata_rata_ujian: 90.13,
    status_penempatan: 'Ditempatkan',
  },
  {
    id_santri: 103,
    no_pendaftaran: '202401003',
    nama_lengkap: 'Budi Santoso',
    jenis_kelamin: 'Laki-laki',
    nilai_bindonesia: 82.0,
    nilai_imla: 85.0,
    nilai_alquran: 88.5,
    nilai_berhitung: 90.0,
    rata_rata_ujian: 86.38,
    status_penempatan: 'Ditempatkan',
  },
  {
    id_santri: 104,
    no_pendaftaran: '202402004',
    nama_lengkap: 'Siti Fatimah',
    jenis_kelamin: 'Perempuan',
    nilai_bindonesia: 88.0,
    nilai_imla: 92.0,
    nilai_alquran: 91.0,
    nilai_berhitung: 85.0,
    rata_rata_ujian: 89.0,
    status_penempatan: 'Ditempatkan',
  },
  {
    id_santri: 105,
    no_pendaftaran: '202401005',
    nama_lengkap: 'Yusuf Ibrahim',
    jenis_kelamin: 'Laki-laki',
    nilai_bindonesia: 90.5,
    nilai_imla: 89.0,
    nilai_alquran: 87.5,
    nilai_berhitung: 91.0,
    rata_rata_ujian: 89.5,
    status_penempatan: 'Belum Ditempatkan',
  },
];

export const mockPenempatan: PenempatanResult[] = [
  {
    id: '1',
    no_pendaftaran: '202401001',
    nama_lengkap: 'Ahmad Fathan',
    jenis_kelamin: 'Laki-laki',
    kampus: 'Gontor 2',
    wakil_pengasuh: 'Ustadz Ridwan Kamil',
  },
  {
    id: '2',
    no_pendaftaran: '202402002',
    nama_lengkap: 'Zainab Aliyah',
    jenis_kelamin: 'Perempuan',
    kampus: 'Gontor Putri 1',
    wakil_pengasuh: 'Ustadzah Aisyah Humaira',
  },
  {
    id: '3',
    no_pendaftaran: '202401003',
    nama_lengkap: 'Budi Santoso',
    jenis_kelamin: 'Laki-laki',
    kampus: 'Gontor 1 Pusat',
    wakil_pengasuh: 'Ustadz Hasanuddin',
  },
  {
    id: '4',
    no_pendaftaran: '202402004',
    nama_lengkap: 'Siti Fatimah',
    jenis_kelamin: 'Perempuan',
    kampus: 'Gontor Putri 2',
    wakil_pengasuh: 'Ustadzah Fatimah Azzahra',
  },
];

export const mockPanitia: Panitia[] = [
  {
    id_panitia: 1,
    username: 'superadmin',
    role: 'Super Admin',
  },
  {
    id_panitia: 2,
    username: 'admin_penempatan_1',
    role: 'Admin Penempatan',
  },
  {
    id_panitia: 3,
    username: 'admin_penempatan_2',
    role: 'Admin Penempatan',
  },
];
